Tarea 1

1._Crea un bucle para obtener el promedio de todos los elementos que se encuentran en las siguientes listas:

In [1]:
L1=[7.2,7.8,6.8,8.0,None,'8.2',5.6,8.2,7.7,7.5,None,5.8]
L2=['6.8',None,6.8,6.1,7.9,9.4,None]
L3=[8.5,'9.0',None,7.7]

In [2]:
lista=L1+L2+L3
print(lista)

[7.2, 7.8, 6.8, 8.0, None, '8.2', 5.6, 8.2, 7.7, 7.5, None, 5.8, '6.8', None, 6.8, 6.1, 7.9, 9.4, None, 8.5, '9.0', None, 7.7]


In [3]:

nueva = []
for i in lista:
    if i is not None:
        nueva.append(i)

print(nueva)

[7.2, 7.8, 6.8, 8.0, '8.2', 5.6, 8.2, 7.7, 7.5, 5.8, '6.8', 6.8, 6.1, 7.9, 9.4, 8.5, '9.0', 7.7]


In [4]:
nueva.remove('8.2')

In [5]:
nueva.remove('6.8')

In [6]:
nueva.remove('9.0')

In [7]:
nueva.append(6.8)
nueva.append(8.2)
nueva.append(9.0)

In [8]:
nueva.sort()

In [9]:
nueva

[5.6,
 5.8,
 6.1,
 6.8,
 6.8,
 6.8,
 7.2,
 7.5,
 7.7,
 7.7,
 7.8,
 7.9,
 8.0,
 8.2,
 8.2,
 8.5,
 9.0,
 9.4]

In [10]:
n=len(nueva)
n

18

In [19]:
suma_total = 0

for i in nueva:
   if i is None:continue
   suma_total += i

   promedio = suma_total / len(nueva)

print(promedio)

7.5


2._Crea un bucle que divida en 3 listas del mismo tamaño a los elementos de las listas anteriores ordenados de menor a mayor.

In [11]:
cad=n/3
cad

6.0

In [12]:
L1_ord = []
L2_ord = []
L3_ord = []

m = 0
while m < cad:
    L1_ord.append(nueva[m])
    L2_ord.append(nueva[m + 6])
    L3_ord.append(nueva[m + 12])
    m += 1

In [13]:
L1_ord

[5.6, 5.8, 6.1, 6.8, 6.8, 6.8]

In [14]:
L2_ord

[7.2, 7.5, 7.7, 7.7, 7.8, 7.9]

In [15]:
L3_ord

[8.0, 8.2, 8.2, 8.5, 9.0, 9.4]

3._Crea una código que reciba del usuario nueve elementos de una matriz cuadrada de 3x3 y que retorne el determinante de la matriz.

In [16]:
import numpy as np

In [26]:
print("Introduce los 9 elementos de una matriz 3x3 (fila por fila):")

# Leer los 9 números del usuario
entrada = []
for i in range(9):
  num = float(input(f"Entrada {i+1}: "))
  entrada.append(num)
matriz = np.array(entrada).reshape((3, 3))

print(matriz)

# Calcular el determinante
det = np.linalg.det(matriz)

print(f"El determinante es: {det}")


Introduce los 9 elementos de una matriz 3x3 (fila por fila):
Entrada 1: 1
Entrada 2: 0
Entrada 3: 0
Entrada 4: 0
Entrada 5: 1
Entrada 6: 0
Entrada 7: 0
Entrada 8: 0
Entrada 9: 1
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
El determinante es: 1.0


4._Crea un código que reciba una cadena de caracteres y arroje la respuesta de si es un estado ó una capital del país.

In [27]:
# Diccionario: capitales por estado
estados_y_capitales = {
    "Aguascalientes": "Aguascalientes",
    "Baja California": "Mexicali",
    "Baja California Sur": "La Paz",
    "Campeche": "San Francisco de Campeche",
    "Chiapas": "Tuxtla Gutiérrez",
    "Chihuahua": "Chihuahua",
    "Ciudad de México": "Ciudad de México",
    "Coahuila": "Saltillo",
    "Colima": "Colima",
    "Durango": "Victoria de Durango",
    "Estado de México": "Toluca",
    "Guanajuato": "Guanajuato",
    "Guerrero": "Chilpancingo",
    "Hidalgo": "Pachuca",
    "Jalisco": "Guadalajara",
    "Michoacán": "Morelia",
    "Morelos": "Cuernavaca",
    "Nayarit": "Tepic",
    "Nuevo León": "Monterrey",
    "Oaxaca": "Oaxaca",
    "Puebla": "Puebla",
    "Querétaro": "Santiago de Querétaro",
    "Quintana Roo": "Chetumal",
    "San Luis Potosí": "San Luis Potosí",
    "Sinaloa": "Culiacán",
    "Sonora": "Hermosillo",
    "Tabasco": "Villahermosa",
    "Tamaulipas": "Ciudad Victoria",
    "Tlaxcala": "Tlaxcala",
    "Veracruz": "Xalapa",
    "Yucatán": "Mérida",
    "Zacatecas": "Zacatecas"
}

# El usuario proporciona un nombre
entrada = input("Ingresa un nombre: ").strip()

# Normalizar para comparación
entrada_normalizada = entrada.lower()

# Buscar el lugar del nombre proporcionado
es_estado = False
es_capital = False

for estado, capital in estados_y_capitales.items():
    if entrada_normalizada == estado.lower():
        es_estado = True
    if entrada_normalizada == capital.lower():
        es_capital = True

#Tiene 4 opciones
if es_estado and es_capital:
    print(f"{entrada} es estado y capital.")
elif es_estado:
    print(f"{entrada} es un estado.")
elif es_capital:
    print(f"{entrada} es una capital.")
else:
    print(f"{entrada} no es ni estado ni capital.")


Ingresa un nombre: peru
peru no es ni estado ni capital.


5._Pide al usuario dos listas de números reales (misma longitud) y calcula su producto escalar usando un bucle for.

In [28]:
# Pedir al usuario la longitud de las listas
n = int(input("¿Cuántos elementos tendran las listas? "))

# Pedir los elementos de la primera lista
print("Introduce los elementos de la primera lista:")
lista_1 = []
for i in range(n):
    x = float(input(f"Elemento {i+1}: "))
    lista_1.append(x)

# Pedir los elementos de la segunda lista
print("Introduce los elementos de la segunda lista:")
lista_2 = []
for i in range(n):
    y = float(input(f"Elemento {i+1}: "))
    lista_2.append(y)

# Calcular el producto escalar
producto_escalar = 0
for i in range(n):
    producto_escalar += lista_1[i] * lista_2[i]

print(f"\nEl producto escalar  es: {producto_escalar}")


¿Cuántos elementos tendran las listas? 1
Introduce los elementos de la primera lista:
Elemento 1: 1
Introduce los elementos de la segunda lista:
Elemento 1: 2

El producto escalar  es: 2.0


6._Utiliza un bucle while True para pedir números al usuario y agregarlos a una lista. Cuando la suma total de los elementos sea mayor a 100, el programa debe detenerse y mostrar la lista y la suma final.

In [22]:
numeros = []
suma_total = 0

print("Ingresa números. El programa se detendrá cuando la suma supere 100.")

while True:
    num = float(input("Número: "))
    numeros.append(num)
    suma_total += num

    if suma_total > 100:
        break

print("\nSuma total:", suma_total)
print("Lista de números ingresados:", numeros)


Ingresa números. El programa se detendrá cuando la suma supere 100.
Número: 13
Número: 15
Número: 65
Número: 20

Suma total: 113.0
Lista de números ingresados: [13.0, 15.0, 65.0, 20.0]


7._Crea una lista vacía y presenta al usuario un menú como este dentro de un while True:

In [29]:
lista = []

while True:
    print("\nMenú:")
    print("1. Agregar número")
    print("2. Mostrar lista")
    print("3. Salir")

    opcion = input("Seleccione una opción: ")

    if opcion == "1":
        numero = float(input("Ingrese un número: "))
        lista.append(numero)
        print("Número agregado.")
    elif opcion == "2":
        print("Lista actual:", lista)
    elif opcion == "3":
        print("Saliendo del programa.")
        break
    else:
        print("Opción no válida. Intente de nuevo.")



Menú:
1. Agregar número
2. Mostrar lista
3. Salir
Seleccione una opción: 3
Saliendo del programa.
